package com.example.demo.entities;

public enum Motivo {
    CURSO, 
    CURSO_A_COLEGIO, 
    STEAM_SCHOOL, 
    STEAM_YOUNG, 
    CLASE, 
    SOCIALIZACION, 
    SOCIALIZACION_A_COLEGIO, 
    SEMILLERO,
    GRABACION_CARRERA, 
    GRABACION_SEMILLERO,
    GRABACION_EXTERNO,
    SUSTENTACION_PROYECTO_GRADO, 
    PRACTICANTE, 
    INFORME_FINAL
}
